### ISSUE TITLE
Fhir's base url

### ISSUE THREAD

**Issue by longnguyen2306** [dermatologist/fhirql#2]
Hello again,

I am using your boilerplate for an uni project and it is working pretty good so far. However I found out a problem, which could be reproduced just by cloning this repo and run the server.

The URL base will always contains a "*" for example searching every account on server will return: 

"url": "/fhir/*/Account?_pretty=true"

I found out the problem could have something to do with the application.yml

```
hapi:
  fhir:
    version: dstu3
    server:
      path: `/fhir/*`
```
The star in path: /fhir/* can not be removed and I have tried many things to get it works.
